// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_get_daily_boilergram from "./routes/api/get_daily_boilergram.ts";
import * as $index from "./routes/index.tsx";
import * as $GridGame from "./islands/GridGame.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/about.tsx": $about,
		"./routes/api/get_daily_boilergram.ts": $api_get_daily_boilergram,
		"./routes/index.tsx": $index,
	},
	islands: {
		"./islands/GridGame.tsx": $GridGame,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
